# Generated by Django 6.0.1 on 2026-01-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('choice', models.JSONField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('student_password', models.CharField(blank=True, max_length=20, null=True)),
                ('student_dob', models.DateField()),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=10)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodingTestApp.student')),
            ],
        ),
    ]
